steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
        'build',
        '-t', 'us-east1-docker.pkg.dev/ai-content-consultant/${_ARTIFACT_REGISTRY_REPO_ID}/api-service:latest',
        '.'
      ]

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/ai-content-consultant/${_ARTIFACT_REGISTRY_REPO_ID}/api-service:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
        'run', 'deploy', 'api-service',
        '--image', 'us-east1-docker.pkg.dev/ai-content-consultant/${_ARTIFACT_REGISTRY_REPO_ID}/api-service:latest',
        '--region', '${_GCP_REGION}',
        '--platform', 'managed',
        '--quiet'
      ]

# Default substitutions
substitutions:
  _ARTIFACT_REGISTRY_REPO_ID: 'ai-content-consultant-repo'
  _GCP_REGION: 'us-east1'

images:
  - 'us-east1-docker.pkg.dev/ai-content-consultant/${_ARTIFACT_REGISTRY_REPO_ID}/api-service:latest'

options:
  logging: CLOUD_LOGGING_ONLY 